version: "3"
services:
  rs1:
    image: mongo:3.2
    command: mongod --replSet "rs0"
    deploy:
      replicas: 1
    networks:
      - db_net
  rs2:
    image: mongo:3.2
    command: mongod --replSet "rs0"
    deploy:
      replicas: 1
    networks:
      - db_net
  rs3:
    image: mongo:3.2
    command: mongod --replSet "rs0"
    deploy:
      replicas: 1
    networks:
      - db_net
  rs:
    image: sardjv/mongors
    deploy:
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 10
    networks:
      - db_net
networks:
  db_net: